#!/usr/bin/env python3
"""Generate the deterministic session-start view derived from ``tasks/INDEX.md``.

The generated brief is not another task authority. It exposes the small execution view that is
hard to recover from the large outcome ledger: currently worked tasks, open tasks with no other
open task dependency, and open tracks whose recorded dependencies remain actionable.

Run:
  python scripts/generate_session_brief.py
  python scripts/generate_session_brief.py --check
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import check_task_policy as task_policy

OUTPUT = Path("tasks/SESSION-BRIEF.md")
EXECUTION_DISPOSITIONS = frozenset({"in-progress", "in-review", "revision-required", "blocked"})


def _task_path(root: Path, task_id: str) -> str:
    matches = sorted((root / "tasks").glob(f"{task_id}-*.md"))
    if not matches:
        return f"tasks/{task_id}-missing.md"
    return matches[0].relative_to(root).as_posix()


def _open_dependencies(
    row: task_policy.ActiveRow,
    active: dict[str, task_policy.ActiveRow],
) -> list[str]:
    unresolved: list[str] = []
    for dependency in task_policy.dependency_ids(row.depends):
        if dependency.startswith("ADR-") or dependency not in active:
            continue
        disposition = task_policy.status_disposition(active[dependency].status)
        if disposition in task_policy.ACTIONABLE_DISPOSITIONS:
            unresolved.append(dependency)
    return unresolved


def generate(root: Path) -> str:
    previous_tasks = task_policy.TASKS
    task_policy.TASKS = root / "tasks"
    try:
        problems: list[str] = []
        active, retired = task_policy.parse_index_rows(problems)
    finally:
        task_policy.TASKS = previous_tasks
    if problems:
        raise ValueError("; ".join(problems))

    execution: list[task_policy.ActiveRow] = []
    ready: list[task_policy.ActiveRow] = []
    waiting: list[tuple[task_policy.ActiveRow, list[str]]] = []
    closed = 0
    for row in active.values():
        disposition = task_policy.status_disposition(row.status)
        if disposition in EXECUTION_DISPOSITIONS:
            execution.append(row)
            continue
        if disposition not in {"todo", "partial"}:
            closed += 1
            continue
        open_dependencies = _open_dependencies(row, active)
        if open_dependencies:
            waiting.append((row, open_dependencies))
        else:
            ready.append(row)

    lines = [
        "# Session Brief",
        "",
        "Generated from `tasks/INDEX.md` by `python scripts/generate_session_brief.py`.",
        "Do not edit this file by hand. The Index remains the outcome authority; this is only",
        "a deterministic execution view, and an “open dependency” is not an authorization gate",
        "unless the owning task says so.",
        "",
        "## Work in progress",
        "",
    ]
    if execution:
        for row in execution:
            disposition = task_policy.status_disposition(row.status)
            lines.append(
                f"- `{row.task_id}` — {row.title} "
                f"({disposition}; `{_task_path(root, row.task_id)}`)"
            )
    else:
        lines.append("- none")

    lines.extend(
        [
            "",
            "## Actionable with no open recorded task dependency",
            "",
        ]
    )
    if ready:
        for row in ready:
            disposition = task_policy.status_disposition(row.status)
            lines.append(
                f"- `{row.task_id}` — {row.title} "
                f"({disposition}; `{_task_path(root, row.task_id)}`)"
            )
    else:
        lines.append("- none")

    lines.extend(["", "## Open tracks with actionable recorded dependencies", ""])
    if waiting:
        for row, dependencies in waiting:
            dependency_text = ", ".join(f"`{value}`" for value in dependencies)
            lines.append(
                f"- `{row.task_id}` — {row.title}; open dependencies: {dependency_text} "
                f"(`{_task_path(root, row.task_id)}`)"
            )
    else:
        lines.append("- none")

    lines.extend(
        [
            "",
            "## Ledger summary",
            "",
            f"- {len(active)} active-table outcomes",
            f"- {len(retired)} retired tasks",
            f"- {closed} active-table rows already carrying a closed/non-actionable disposition",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=None)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    root = args.root.resolve() if args.root else Path(__file__).resolve().parent.parent
    try:
        expected = generate(root)
    except ValueError as exc:
        print(f"generate_session_brief: cannot parse task index: {exc}", file=sys.stderr)
        return 1
    output = root / OUTPUT
    if args.check:
        actual = output.read_text(encoding="utf-8") if output.is_file() else None
        if actual != expected:
            print(
                "generate_session_brief: tasks/SESSION-BRIEF.md is stale; run "
                "`python scripts/generate_session_brief.py`",
                file=sys.stderr,
            )
            return 1
        print("generate_session_brief: OK")
        return 0

    temporary = output.with_suffix(output.suffix + ".tmp")
    temporary.write_text(expected, encoding="utf-8")
    temporary.replace(output)
    print(f"generate_session_brief: wrote {OUTPUT} ({len(expected.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
